version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: mybooru-web
    environment:
      - CDN_BASE_URL=http://localhost/files
    volumes:
      - ./static/images:/app/static/images
      - ./db:/app/db
    env_file:
      - .env

  imagor:
    image: shumc/imagor
    volumes:
      - ./static/images:/mnt/data
    environment:
      PORT: 8000
      IMAGOR_UNSAFE: 1 # unsafe URL for testing
      FILE_LOADER_BASE_DIR: /mnt/data # enable file loader by specifying base dir
      FILE_STORAGE_BASE_DIR: /mnt/data # enable file storage by specifying base dir
      FILE_STORAGE_MKDIR_PERMISSION: 0755 # optional
      FILE_STORAGE_WRITE_PERMISSION: 0666 # optional
      FILE_RESULT_STORAGE_MKDIR_PERMISSION: 0755 # optional
      FILE_RESULT_STORAGE_WRITE_PERMISSION: 0666 # optional

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
      - imagor
