FROM rust

RUN apt-get update && apt-get install -y \
    clang \
    libavcodec-dev \
    libavformat-dev \
    libavutil-dev \
    libavfilter-dev \
    libavdevice-dev \
    pkg-config \
    libssl-dev
