name: Release Crate and Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Login to crates.io
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish to crates.io
        run: cargo publish --no-verify

  docker-sqlite:
    needs: publish-crate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push SQLite image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker buildx build \
            --build-arg BUILD_FEATURES=sqlite \
            --tag ghcr.io/${{ github.repository }}:${VERSION}-sqlite \
            --tag ghcr.io/${{ github.repository }}:latest-sqlite \
            --tag ghcr.io/${{ github.repository }}:latest \
            --push \
            -f docker/Dockerfile .

  docker-postgres:
    needs: publish-crate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Postgres image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker buildx build \
            --build-arg BUILD_FEATURES=postgres \
            --tag ghcr.io/${{ github.repository }}:${VERSION}-postgres \
            --tag ghcr.io/${{ github.repository }}:latest-postgres \
            --push \
            -f docker/Dockerfile .
