name: Release Crate and Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Login to crates.io
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish to crates.io
        run: cargo publish --no-verify

  docker:
    needs: publish-crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set additional tags
        id: tags
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MINOR=$(echo $VERSION | grep -oE '^v?[0-9]+\.[0-9]+')
          echo "TAGS=ghcr.io/${{ github.repository }}:$VERSION,ghcr.io/${{ github.repository }}:$MINOR,ghcr.io/${{ github.repository }}:latest" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ env.TAGS }}
